@startuml BookStore_State_Diagram_admin
hide empty description

state "index.html" as i{
  i: jwt\nroles\nexpiration

[*] --> Login : Logout

state "BookSearch" as bs1 {
  state c1 <<choice>>
  [*] --> SearchForm : type in criteria
  SearchForm --> Waiting : Button "Search"
  Waiting --> c1 : SearchResult received
  state "SearchResult" as sr1{
    state "ErrorMessage" as e1
    state FoundBooks
  }
  c1 --> e1 : no book found
  c1 --> FoundBooks : AL 1 book found
}

state c2 <<choice>>
[*] --> CreateBook : menu option "New Book"
CreateBook -down-> c2 : Button "OK"
c2 -up-> ErrorMessage : incorrect data
ErrorMessage -up-> CreateBook
c2 --> Home : correct data

state c3 <<choice>>
Home <-up- c3 : correct data
c3 -down-> UpdateBook : incorrect data
UpdateBook -up-> c3 : Button "OK"

FoundBooks --> DetailsBook : click link
UpdateBook <-up- DetailsBook: Button "update"
[*] --> bs1 : menu option "Search"
}

footer (c) Niklas Tremmel(G3)

@enduml
